### ISSUE TITLE
Accept className for compatibility with styled-components

### ISSUE THREAD

**Issue by wswoodruff** [material-native/material-native#34]
Styled-components can wrap arbitrary 3rd party components as long as they receive and apply the `className` prop. The FAB button and possibly some others don't currently do that, seems like a simple enough fix. Thoughts?

**Comment by dantman** [comment]
Can you give a more detailed explanation of what you're talking about? I don't understand what `className` has to to with `material-native` components, this library isn't intended to be used on the web.

**Comment by wswoodruff** [comment]
[styled-components](https://www.styled-components.com/docs/basics#react-native) works with react-native, and I like using it in part for that reason. There's a syntax you can use with `styled-components` that works [only if you pass down className](https://www.styled-components.com/docs/advanced#styling-normal-react-components)

example:
```js
// styles.js

const { FAB } = require('material-native');
const { default: styled } = require('styled-components/native');

module.exports = {
     FAB: styled(FAB)`
        position: absolute;
        right: 10px;
        bottom: 10px;
    `
};
```
Then when I require FAB from styles.js, those styles will be applied to it.

**Comment by dantman** [comment]
@wswoodruff That library's documentation says "If you are using react-native keep in mind to use style instead of className.", I don't see anything there that suggests that it requires that React Native components accept the `className` property.

**Comment by wswoodruff** [comment]
Oh that's weird I hadn't seen that before. I'll might write back how I solved it once I figure it out

**Comment by wswoodruff** [comment]
My bad, figured out I was just having difficulty setting the bottom prop in react-native. I'm trying to position a FAB in the bottom right corner while having content underneath it scroll in a ScrollView, no luck so far!

**Comment by dantman** [comment]
I'm not sure how you're using it / how it's breaking in your app so I can't suggest any fixes.

**Comment by wswoodruff** [comment]
Here's what made all the difference. I checked out your Material Explorer and saw how you were putting a FAB in the bottom right corner.

I had my FAB in JSX listed on top of the scrollview it was supposed to float on top of.

As soon as I put the FAB below the scrollview, without changing anything else, it fixed the issue.

**Comment by dantman** [comment]
Ah, just the usual z-index issue. The other common mistake would be putting something inside the ScrollView, which doesn't work because RN doesn't have anything like `position: fixed;`.

**Comment by wswoodruff** [comment]
Having the background color set I think was the major offender in my case
