### ISSUE TITLE
Unable to supply a React component as Button text prop

### ISSUE THREAD

**Issue by jpaas** [material-native/material-native#35]
I was trying to localize a button using react-intl, so I supplied a react-intl FormattedMessage component to the text prop on Button, but it results in a couple of strange errors. This is with `0.0.0-alpha.12`

The first error:

```

ExceptionsManager.js:73 Did not get valid calls back from JS: [[39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,49,49,39,39,39,39,39,39,39,39,39,39,39,8,53,53,53,53,53,53,53],[5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,5,3,3,5,3,3,3,2,6,5,5,5,5,5,5,5,5,5,5,1,3,3,3,3,3,3,0],[[2,"RCTView",1,{"pointerEvents":"box-none","flex":1}],[3,"RCTView",1,{"pointerEvents":"box-none","flex":1}],[4,"RCTView",1,{"onLayout":true,"overflow":"hidden","flex":1}],[5,"RCTView",1,{"alignItems":"stretch","flexDirection":"row","flex":1}],[6,"RCTView",1,null],[7,"RCTView",1,{"right":0,"left":0,"bottom":0,"top":0,"position":"absolute"}],[8,"RCTView",1,{"overflow":"hidden","flex":1}],[9,"RCTView",1,{"position":"absolute","justifyContent":"center","bottom":0,"alignItems":"center","left":0,"right":0,"backgroundColor":4294967040,"top":0}],[10,"RCTView",1,{"alignItems":"center","justifyContent":"center"}],[12,"RCTActivityIndicatorView",1,{"size":"large","hidesWhenStopped":true,"width":36,"animating":true,"height":36,"color":4288256409}],[10,[12]],[9,[10]],[8,[9]],[7,[8]],[5,[6,7]],[13,"RCTView",1,{"position":"absolute"}],[4,[5,13]],[3,[4]],[14,"RCTView",1,{"position":"absolute"}],[2,[3,14]],[1,[2]],["url"],[68,69],[6,"RCTView",{"right":0,"left":0,"bottom":0,"top":0,"position":"absolute"}],[15,"RCTView",1,{"overflow":"hidden","flex":1}],[16,"RCTView",1,{"backgroundColor":0,"flex":1}],[17,"RCTView",1,{"zIndex":0,"flex":1}],[18,"RCTView",1,{"onLayout":true,"flex":1}],[19,"RCTView",1,{"backgroundColor":4278190080,"flexDirection":"column-reverse","flex":1}],[20,"RCTView",1,{"flex":1}],[22,"RCTView",1,{"right":0,"position":"absolute","pointerEvents":"auto","backgroundColor":4293519855,"shadowRadius":5,"transform":[{"translateX":0},{"translateY":0}],"opacity":1,"shadowOpacity":0.2,"bottom":0,"left":0,"shadowColor":4278190080,"shadowOffset":{"height":0,"width":0},"top":0}],[23,"RCTView",1,{"flex":1}],[24,"RCTView",1,{"alignItems":"center","justifyContent":"center","backgroundColor":4294967295,"padding":8}],["Converting circular structure to JSON",[{"lineNumber":1947,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"MessageQueue.enqueueNativeCall","column":14},{"lineNumber":1746,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"Object.fn [as createView]","column":21},{"lineNumber":23717,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"Constructor.mountComponent","column":26},{"lineNumber":22011,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"Object.mountComponent","column":39},{"lineNumber":22368,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"ReactCompositeComponentWrapper.performInitialMount","column":40},{"lineNumber":22320,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"ReactCompositeComponentWrapper.mountComponent","column":165},{"lineNumber":22011,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"Object.mountComponent","column":39},{"lineNumber":22368,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"ReactCompositeComponentWrapper.performInitialMount","column":40},{"lineNumber":22320,"file":"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false","methodName":"ReactCompositeComponentWrapper.mountComponent","column":165}],1],["didSendNetworkData"],["didReceiveNetworkResponse"],["didReceiveNetworkData"],["didReceiveNetworkIncrementalData"],["didReceiveNetworkDataProgress"],["didCompleteNetworkResponse"],[{"method":"POST","headers":{"content-type":"text/plain;charset=UTF-8"},"responseType":"text","data":{"trackingName":"unknown","string":"{\"stack\":[{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"MessageQueue.enqueueNativeCall\",\"lineNumber\":1947,\"column\":14},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"Object.fn [as createView]\",\"lineNumber\":1746,\"column\":21},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"Constructor.mountComponent\",\"lineNumber\":23717,\"column\":26},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"Object.mountComponent\",\"lineNumber\":22011,\"column\":39},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"ReactCompositeComponentWrapper.performInitialMount\",\"lineNumber\":22368,\"column\":40},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"ReactCompositeComponentWrapper.mountComponent\",\"lineNumber\":22320,\"column\":165},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"Object.mountComponent\",\"lineNumber\":22011,\"column\":39},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"ReactCompositeComponentWrapper.performInitialMount\",\"lineNumber\":22368,\"column\":40},{\"file\":\"http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false\",\"methodName\":\"ReactCompositeComponentWrapper.mountComponent\",\"lineNumber\":22320,\"column\":165}]}"},"withCredentials":true,"timeout":0,"incrementalUpdates":false,"url":"http://localhost:8081/symbolicate"},107]],12]
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:67
logToConsole @ RCTLog.js:43
logIfNoNativeHook @ RCTLog.js:29
__callFunction @ MessageQueue.js:306
(anonymous) @ MessageQueue.js:108
__guard @ MessageQueue.js:269
MessageQueue.callFunctionReturnFlushedQueue @ MessageQueue.js:107
t @ RNDebuggerWorker.js:1
```

The second:
```
ExceptionsManager.js:73 Did not get valid calls back from JS: [[39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,49,49,39,39,39,39,39,39,39,39,39,39,39,8,53,53,53,53,53,53,53],[5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,5,3,3,5,3,3,3,2,6,5,5,5,5,5,5,5,5,5,5,1,3,3,3,3,3,3,0],[[2,"RCTView",1,{"pointerEvents...

  | reactConsoleErrorHandler | @ | ExceptionsManager.js:73
-- | -- | -- | --
  | console.error | @ | YellowBox.js:67
  | logToConsole | @ | RCTLog.js:43
  | logIfNoNativeHook | @ | RCTLog.js:29
  | __callFunction | @ | MessageQueue.js:306
  | (anonymous) | @ | MessageQueue.js:108
  | __guard | @ | MessageQueue.js:269
  | MessageQueue.callFunctionReturnFlushedQueue | @ | MessageQueue.js:107
  | t | @ | RNDebuggerWorker.js:1


```

**Comment by jpaas** [comment]
I'm trying to do this...

```JSX
<Button
  onPress={() => this.handleAdd()}
  accent
  raised
  text={<FormattedMessage {...translations.addButton} />}
/>
```

The other consideration would be to have Button component render its children inside the button instead of using a `text` prop.

**Comment by dantman** [comment]
What are the values for `translations.addButton`?

**Comment by jpaas** [comment]
```JSX
import { defineMessages, FormattedMessage } from "react-intl"
const translations = defineMessages({
  addButton: {
    id: "add-button",
    defaultMessage: "Add",
    description: "The label of the button used to add new entities",
  },
})
```

At runtime, translations.addButton evaluates to:
```javascript
 {id: "add-button", defaultMessage: "Add"}
```

**Comment by dantman** [comment]
Took a bit of work to recreate:
https://snack.expo.io/rJ_UILJ2b

**Comment by dantman** [comment]
**facepalm**

This is the issue:
```js
accessibilityLabel={text}
```

I expected `text` to always be a string and used it as the accessibility text. This is done because iOS has a strange quirk where it decides to add extra space characters. ie: without it `<Button text="LOGIN" />` becomes `"LOGIN  "` in accessibility text making it difficult to target in UI tests / screenshot tests.

I'm not sure this is worth trying to "fix" by making the accessibility text conditional whether you pass a string or not (making the fix for that bug silently disappear if you pass a text component instead of a string). It would make sense if it made sense to allow rich `<Text>` components to be passed to allow rich control over the text styling. But it doesn't, Material Design's button design is very rigid, hence why Button was given a `text` prop expecting a string instead of having `children`.

The "fix" for this will probably be when I setup flow types and automatic propTypes that just mark `text` as a string prop and give you a warning when you pass something that is not a string.

This isn't really a loss as far as react-intl goes anyways, since this way of using `FormattedMessage` is only really supposed to be used/necessary in children where the `<Text>` isn't already setup.

The correct way to use `FormattedMessage` with a component expecting a string is this code (you'll have to do this anyways for many other props like `placeholder`):
```js
<FormattedMessage {...translations.addButton}>
  {(addButton) => (
    <Button
      onPress={() => this.handleAdd()}
      accent
      raised
      text={addButton}
    />
  )}
</FormattedMessage>
```

I know this looks a little verbose, however that's just the nature of react-intl (and why it never looked appealing to me personally).

It could be easier if someone were to create a HOC that automatically did this, so you could write:
```js
import {Button as RawButton} from 'material-native';
import withIntlProps from 'with-intl-props';
const Button = withIntlProps(Button);

<Button
  onPress={() => this.handleAdd()}
  accent
  raised
  text={<FormattedMessage {...translations.addButton} />}
/>
```

The HOC would just look at props for any non-children format component, omit it from the props list, and wrap the component with a cloneElement of the Format element that instead uses the function format and passes the arg as the prop to the wrapped component.

**Comment by jpaas** [comment]
Thanks for investigating this @dantman! Another alternative is to use the react-intl `formatMessage` function. At one time, they used to discourage its use, but I can't find that warning anymore. The only downside is that the intl prop has to be injected:

```JSX
import { injectIntl } from "react-intl"


render() {
  const { intl: formatMessage } = this.props
...
  <Button
    onPress={() => this.handleAdd()}
    accent
    raised
    text={formatMessage(translations.addButton)}
  />
...
}

export injectIntl(MyComponent)
```

But the idea of being able to provide a React component as the button content offers a whole lot of flexibility that might be a good escape valve from a lot of future discussions about how to make Button do "X".

Here's a good example, in our app, we have submit buttons that replace the text with a spinning activity indicator when the form is submitting.

**Comment by dantman** [comment]
> But the idea of being able to provide a React component as the button content offers a whole lot of flexibility that might be a good escape valve from a lot of future discussions about how to make Button do "X".
> 
> Here's a good example, in our app, we have submit buttons that replace the text with a spinning activity indicator when the form is submitting.

I'm aware there will be requests like those, but I intend to just mark those kind as `wontfix` with the same answer.

This library's intent is to create components that follow Material Design, not general purpose components that can be modified to do anything you want them to. Supporting non-MD behaviours desired by individual users just makes hacks pile up bloating the library and making the code using the hack messy. So I'm not going to add anything to the high level components to support modifying them in non-MD ways.

Buttons especially have no good reason to add ways to mutate them like that. material-native already provides the Ripple (in this specific case RectRipple), typography helpers, colours, shades, theme handling, etc... so you can build whatever non-standard material-design inspired components out of low level MD concepts. The button component is really simple, almost half the code is just handling the different button styles, color modes, etc... that aren't relevant if you're doing something custom.

For a real example, in the app I'm working on for a client they wanted a login button on the login page that didn't follow MD, it was much larger than a MD button is supposed to be. So I just wrote a simple custom button component:
https://gist.github.com/dantman/f7dfd6c5db251ac68d8ab84a3cd75fe7

**Comment by dantman** [comment]
React Native fixed the bug causing trailing spaces that required the `accessibilityLabel` so I've removed it. **However** I still don't consider passing non-strings to `text` to supported. So even though this error will go away for now, you **will** get flow/PropTypes errors in the future if you pass strings.
